import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { FormEvent, useState } from 'react'
import { useMutateAuth } from '@/hooks/useMutateAuth'

const inter = Inter({ subsets: ['latin'] })

export default function Auth() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <h1>テスト</h1>
        </div>
      </main>
    </>
  )
}
